# linear and angular speed limits for the robot
max_v: 0.4 # m/s
max_w: 1.5 # rad/s
# observation rate fo the robot
frame_rate: 4 # Hz

# topic names (modify for different robots/nodes)
# vel_teleop_topic: "/cmd_vel_mux/input/teleop" 
# vel_navi_topic: "/cmd_vel_mux/input/navi"
vel_teleop_topic: "/locobot/mobile_base/commands/velocity"
vel_navi_topic: "/locobot/mobile_base/commands/velocity"
